// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UCSC.SWFS.SRV.Entity.Context;

#nullable disable

namespace UCSC.SWFS.SRV.Entity.Migrations
{
    [DbContext(typeof(SWFSDbContext))]
    [Migration("20230906201504_addeddeviceandsensors")]
    partial class addeddeviceandsensors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("deviceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("devicename");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("devicetype");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<float>("MaxValue")
                        .HasColumnType("real")
                        .HasColumnName("maxvalue");

                    b.Property<float>("MinValue")
                        .HasColumnType("real")
                        .HasColumnName("minvalue");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plantid");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("DeviceId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plantid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantId"));

                    b.Property<int>("ColumnId")
                        .HasColumnType("integer")
                        .HasColumnName("columnid");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdon");

                    b.Property<int>("FertilizerRequirement")
                        .HasColumnType("integer")
                        .HasColumnName("fertilizerrequirement");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("healthstatus");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plantname");

                    b.Property<string>("PlantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planttype");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("plantingdate");

                    b.Property<int>("RecLightIntensity")
                        .HasColumnType("integer")
                        .HasColumnName("reclightintensity");

                    b.Property<int>("RecSoilMoisture")
                        .HasColumnType("integer")
                        .HasColumnName("recsoilmoisture");

                    b.Property<int>("RecTemperatureMax")
                        .HasColumnType("integer")
                        .HasColumnName("rectemperaturemax");

                    b.Property<int>("RecTemperatureMin")
                        .HasColumnType("integer")
                        .HasColumnName("rectemperaturemin");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rowid");

                    b.Property<int>("WaterRequirement")
                        .HasColumnType("integer")
                        .HasColumnName("waterrequirement");

                    b.HasKey("PlantId");

                    b.HasAlternateKey("RowId", "ColumnId");

                    b.ToTable("plants");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.PlantTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("taskid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdon");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("deviceid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("endtime");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<DateTime?>("NextIterationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("nextiterationtime");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("scheduleid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taskdescription");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taskname");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("TaskId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("planttask");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scheduleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdon");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enddatetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startdatetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedby");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.PlantTask", b =>
                {
                    b.HasOne("UCSC.SWFS.SRV.Entity.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCSC.SWFS.SRV.Entity.Entities.Schedule", null)
                        .WithMany("PlantTasks")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("UCSC.SWFS.SRV.Entity.Entities.Schedule", b =>
                {
                    b.Navigation("PlantTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
